#!/bin/bash

PRIVOXYCONFIG="$HOME/.gumbode/privoxy/conf/config"

WEINRE=1
JSCONSOLE=0
AARDWOLF=0

# we'll overwrite which things to inject in the ini file, if any
source "$HOME/.gumbode/privoxy/inject.ini"

if [ $WEINRE -eq 1 ]; then
	echo "actionfile weinre.action" >> "$PRIVOXYCONFIG"
	echo "filterfile weinre.filter" >> "$PRIVOXYCONFIG"
fi

if [ $JSCONSOLE -eq 1 ]; then
	# prefix
	JSCONSOLE_FILES="$HOME/.gumbode/privoxy/conf/jsconsole."

	# generate a new key for JSConsole
	JSCONSOLE_KEY_NEW="$(python  -c 'import uuid; print uuid.uuid1()')"
	# replace the old key with the new one
	sed -i '' -e 's|'$(cat "$HOME/.gumbode/privoxy/conf/jsconsole.key")'|'"$JSCONSOLE_KEY_NEW"'|' "$JSCONSOLE_FILES.filter"
	# store the new key
	echo $JSCONSOLE_KEY_NEW > "$JSCONSOLE_FILES.key"
	
	echo "actionfile jsconsole.action" >> "$PRIVOXYCONFIG"
	echo "filterfile jsconsole.filter" >> "$PRIVOXYCONFIG"
fi

if [ $AARDWOLF -eq 1 ]; then
	echo "actionfile aardwolf.action" >> "$PRIVOXYCONFIG"
	echo "filterfile aardwolf.filter" >> "$PRIVOXYCONFIG"
fi

/usr/local/sbin/privoxy --no-daemon "$PRIVOXYCONFIG"