#!/bin/bash

HOST_IP="$1"

PRIVOXY_DIR="$(pwd)/privoxy"
PRIVOXY_HOST="$HOST_IP"
PRIVOXY_PORT="8118"

WEINRE_HOST="$HOST_IP:37128"
AARDWOLF_HOST="$HOST_IP:8500"

JSCONSOLE_HOST="jsconsole.com"
JSCONSOLE_KEY="$(python  -c 'import uuid; print uuid.uuid1()')"
# echo 'jsconsole key: '$JSCONSOLE_KEY
# open 'http://jsconsole.com/?%3Alisten%20'$JSCONSOLE_KEY

rm -rf "$HOME/.gumbode/privoxy/conf" > /dev/null 2>&1
mkdir -p "$HOME/.gumbode/privoxy/conf" > /dev/null 2>&1
cp privoxy/conf/default/* "$HOME/.gumbode/privoxy/conf"

PWD="$(pwd)"

cd "$HOME/.gumbode/privoxy/conf"
FILELIST="$(ls .)"

for FILE in $FILELIST
do
	if [ -f "$FILE" ]; then
		sed -i '' \
			-e 's|{{PRIVOXY_HOST}}|'"$PRIVOXY_HOST"'|g' \
			-e 's|{{PRIVOXY_PORT}}|'"$PRIVOXY_PORT"'|g' \
			-e 's|{{PRIVOXY_DIR}}|'"$PRIVOXY_DIR"'|g' \
			-e 's|{{AARDWOLF_HOST}}|'"$AARDWOLF_HOST"'|g' \
			-e 's|{{WEINRE_HOST}}|'"$WEINRE_HOST"'|g' \
			-e 's|{{JSCONSOLE_HOST}}|'"$JSCONSOLE_HOST"'|g' \
			-e 's|{{JSCONSOLE_KEY}}|'"$JSCONSOLE_KEY"'|g' \
		"$FILE"
	fi
done

cd "$PWD"

# /usr/local/sbin/privoxy --no-daemon "$PRIVOXY_DIR/conf/config"