#!/bin/bash

WEB_DIR="$2"

if [ "$WEB_DIR" == "" ]; then
	read -e -p "Enter the path to your static JS files: " WEB_DIR
fi

if [ ! -d "$HOME/.gumbode/aardwolf" ]; then
	ln -sfh "$(pwd)/aardwolf" "$HOME/.gumbode/aardwolf"
fi

echo -e "WEB_DIR='$WEB_DIR'" >> "$HOME/.gumbode/aardwolf.conf"